import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve("tests/fixtures/contracts/1.0");
const at = "2099-01-01T01:02:03.000Z";
const runId = "RUN-20990101-010203-DEMO";
const rendererConfig = {
  renderer_config_id: "RCFG-PHASE4B-001",
  renderer_id: "PLAYWRIGHT_HTML_CSS",
  renderer_version: "1.0.0",
  runtime_package: "playwright-core",
  runtime_package_version: "1.62.1",
  browser_family: "CHROMIUM",
  browser_channel: "PLAYWRIGHT_MANAGED",
  browser_path_reference: "EXTERNAL_RENDERER_CACHE",
  headless: true,
  viewport: { width: 1242, height: 1660 },
  device_scale_factor: 1,
  locale: "zh-CN",
  timezone: "Asia/Shanghai",
  color_scheme: "light",
  reduced_motion: "reduce",
  screenshot_options: {
    type: "png",
    animations: "disabled",
    caret: "hide",
    scale: "css",
    omit_background: false,
  },
  network_policy: "BLOCK_ALL",
  font_policy: "SYSTEM_CJK_STACK",
  animation_policy: "DISABLED",
  time_policy: "NO_DYNAMIC_TIME",
  random_policy: "NO_RANDOM_VALUES",
  timeout_ms: 30000,
  schema_version: "1.0.0",
  extensions: {},
};
const asset = (id: string, role: "BACKGROUND" | "RENDERED_PAGE", relativePath: string) => ({
  asset_id: id,
  asset_role: role,
  asset_type: "IMAGE",
  mime_type: role === "BACKGROUND" ? "image/svg+xml" : "image/png",
  relative_path: relativePath,
  source_type: role === "BACKGROUND" ? "PROGRAMMATIC" : "RENDERED",
  source_adapter: "PlaywrightHtmlCssRendererAdapter",
  source_run_id: runId,
  source_generation_id: "GEN-PHASE4B-001",
  version: 1,
  width: 1242,
  height: 1660,
  file_size: 4096,
  checksum: "a".repeat(64),
  created_at: at,
  extensions: {},
});
const environment = {
  renderer_environment_id: "RENV-PHASE4B-001",
  renderer_id: "PLAYWRIGHT_HTML_CSS",
  renderer_version: "1.0.0",
  node_version: "v24.19.0",
  platform: "darwin",
  architecture: "arm64",
  playwright_version: "1.62.1",
  chromium_version: "Chromium 145.0.7632.6",
  headless_mode: "HEADLESS",
  viewport: { width: 1242, height: 1660 },
  device_scale_factor: 1,
  locale: "zh-CN",
  timezone: "Asia/Shanghai",
  color_scheme: "light",
  reduced_motion: "reduce",
  screenshot_options: rendererConfig.screenshot_options,
  resolved_fonts: [
    { role: "TITLE", family: "PingFang SC" },
    { role: "BODY", family: "PingFang SC" },
  ],
  font_profile_hash: "b".repeat(64),
  network_requests_attempted: 0,
  network_requests_blocked: 0,
  environment_fingerprint: "c".repeat(64),
  created_at: at,
  run_id: runId,
  schema_version: "1.0.0",
  extensions: {},
};
const capability = {
  capability_report_id: "RCAP-PHASE4B-001",
  renderer_id: "PLAYWRIGHT_HTML_CSS",
  node_version: "v24.19.0",
  platform: "darwin",
  architecture: "arm64",
  playwright_core_version: "1.62.1",
  playwright_setup_version: "1.62.1",
  browser_installation_status: "INSTALLED",
  browser_family: "CHROMIUM",
  browser_version: "145.0.7632.6",
  browser_executable_hash_or_version: "145.0.7632.6",
  browser_path_policy: "EXTERNAL_CACHE",
  browser_launch_status: "PASSED",
  font_availability: ["PingFang SC"],
  font_fallback_status: "PRIMARY",
  supported_visual_modes: ["EDITORIAL_SERIES"],
  supported_asset_strategies: ["PROGRAMMATIC_GRAPHIC"],
  unsupported_asset_strategies: ["GENERATED_BACKGROUND"],
  network_blocking_status: "PASSED",
  plugin_root_write_status: "READ_ONLY",
  plugin_data_write_status: "WRITABLE",
  warnings: [],
  blocking_errors: [],
  overall_status: "READY",
  checked_at: at,
  schema_version: "1.0.0",
  extensions: {},
};
const template = {
  template_id: "TPL-EDITORIAL-COVER",
  template_version: "1.0.0",
  template_name: "Restrained editorial cover",
  supported_visual_modes: ["EDITORIAL_SERIES"],
  supported_page_roles: ["COVER"],
  supported_asset_strategies: ["PROGRAMMATIC_GRAPHIC"],
  html_template_hash: "d".repeat(64),
  css_template_hash: "e".repeat(64),
  component_library_version: "1.0.0",
  allowed_components: ["CANVAS", "GRAPHIC_LAYER", "TEXT_LAYER"],
  allowed_css_properties: ["position", "font-size", "color"],
  allowed_layout_primitives: [
    "RECTANGLE",
    "ROUNDED_CARD",
    "LINE",
    "DIVIDER",
    "CIRCLE",
    "NUMBER_MARKER",
    "BRACKET",
    "CONNECTOR",
    "GRID",
    "FRAME",
    "ACCENT_BLOCK",
  ],
  required_typography_roles: ["TITLE", "BODY", "PAGE_NUMBER"],
  required_color_roles: ["BACKGROUND", "PRIMARY_TEXT", "ACCENT", "SECONDARY_TEXT"],
  network_allowed: false,
  javascript_allowed: "INTERNAL_MEASUREMENT_ONLY",
  arbitrary_html_allowed: false,
  arbitrary_css_allowed: false,
  created_at: at,
  schema_version: "1.0.0",
  extensions: {},
};
const plan = {
  first_page_production_plan_id: "FPPP-PHASE4B-001",
  project_id: "PRJ-20990101-DEMO",
  content_id: "C-0001",
  page_number: 1,
  page_role: "COVER",
  content_version: "CV-1",
  copy_version: "CV-1",
  visual_plan_version: "VV-1",
  first_page_version: "FPV-1",
  copy_snapshot_hash: "f".repeat(64),
  visual_handoff_ref: "projects/demo/runs/run/visual/visual-handoff-package.json",
  visual_handoff_hash: "1".repeat(64),
  page_visual_plan_id: "PVP-DEMO-01",
  renderer_config: rendererConfig,
  renderer_environment_requirement: {
    platform: "darwin",
    architecture: "arm64",
    browser_family: "CHROMIUM",
    browser_required: true,
    font_profile_required: true,
  },
  template_id: "TPL-EDITORIAL-COVER",
  template_version: "1.0.0",
  asset_strategy: "PROGRAMMATIC_GRAPHIC",
  programmatic_graphic_plan: {
    graphic_id: "PG-PHASE4B-001",
    primitives: ["FRAME", "LINE", "NUMBER_MARKER"],
    contains_formal_copy: false,
    contains_remote_assets: false,
  },
  text_layer_plan: [
    {
      layer_id: "TITLE",
      role: "TITLE",
      exact_text: "先别急着相信专业",
      source_hash: "2".repeat(64),
    },
  ],
  font_resolution_plan: [{ role: "TITLE", font_stack: ["PingFang SC", "sans-serif"] }],
  layout_measurement_plan: [
    "BOUNDING_CLIENT_RECT",
    "SCROLL_SIZE",
    "CLIENT_SIZE",
    "COMPUTED_FONT",
    "LINE_COUNT",
    "VISIBILITY",
    "SAFE_AREA",
    "CANVAS_SCROLL",
  ],
  expected_outputs: [
    "BACKGROUND_SVG",
    "COMPILED_HTML",
    "FIRST_PAGE_PNG",
    "GENERATION_MANIFEST",
    "RENDER_REPORT",
    "QA_REPORT",
    "PRODUCTION_REPORT",
    "ENVIRONMENT_EVIDENCE",
  ],
  qa_requirements: ["Exact copy", "No overflow"],
  live_write_required: true,
  explicit_confirmation: true,
  idempotency_key: "phase4b-demo-first-page-v1",
  plan_hash: "3".repeat(64),
  created_at: at,
  run_id: runId,
  schema_version: "1.0.0",
  extensions: {},
};
const report = {
  first_page_production_report_id: "FPPR-PHASE4B-001",
  project_id: "PRJ-20990101-DEMO",
  content_id: "C-0001",
  content_version: "CV-1",
  copy_version: "CV-1",
  visual_plan_version: "VV-1",
  first_page_version: "FPV-1",
  production_plan_ref: "projects/demo/runs/run/outputs/first-page/first-page-production-plan.json",
  renderer_environment_ref:
    "projects/demo/runs/run/outputs/first-page/renderer-environment-evidence.json",
  generation_manifest_ref: "projects/demo/runs/run/outputs/first-page/generation-manifest.json",
  render_report_ref: "projects/demo/runs/run/outputs/first-page/render-report.json",
  qa_report_ref: "projects/demo/runs/run/outputs/first-page/first-page-qa-report.json",
  background_asset_ref: asset(
    "AST-BACKGROUND-01",
    "BACKGROUND",
    "projects/demo/runs/run/outputs/first-page/01-cover-background_v001.svg",
  ),
  rendered_asset_ref: asset(
    "AST-RENDERED-01",
    "RENDERED_PAGE",
    "projects/demo/runs/run/outputs/first-page/01-cover_v001.png",
  ),
  output_width: 1242,
  output_height: 1660,
  output_format: "PNG",
  output_checksum: "a".repeat(64),
  copy_fidelity_status: "PASS",
  layout_status: "PASS",
  safe_area_status: "PASS",
  font_status: "PASS",
  network_status: "PASS_NO_ATTEMPTS",
  ready_for_g4: true,
  blocking_reasons: [],
  warnings: [],
  created_at: at,
  run_id: runId,
  schema_version: "1.0.0",
  extensions: {},
};
const review = {
  first_page_review_id: "FPR-PHASE4B-001",
  project_id: "PRJ-20990101-DEMO",
  content_id: "C-0001",
  content_version: "CV-1",
  copy_version: "CV-1",
  visual_plan_version: "VV-1",
  first_page_version: "FPV-1",
  asset_checksum: "a".repeat(64),
  decision: "APPROVE",
  overall_comment: "Approved fictional fixture.",
  layout_feedback: "",
  typography_feedback: "",
  color_feedback: "",
  hierarchy_feedback: "",
  graphic_feedback: "",
  copy_feedback: "",
  requested_changes: [],
  revision_classification: "NONE",
  reviewer_role: "OPERATOR",
  source_run_id: runId,
  created_at: at,
  schema_version: "1.0.0",
  extensions: {},
};
const reviseReview = {
  ...review,
  first_page_review_id: "FPR-PHASE4B-R2-001",
  decision: "REVISE",
  overall_comment: "Revise cover conversion copy and global visual direction.",
  requested_changes: ["Route through CONTENT_COPY and GLOBAL_VISUAL_DIRECTION."],
  revision_classification: "CONTENT_COPY",
  revision_routes: ["CONTENT_COPY", "GLOBAL_VISUAL_DIRECTION"],
};
const revision = {
  first_page_revision_plan_id: "FPRP-PHASE4B-001",
  project_id: "PRJ-20990101-DEMO",
  content_id: "C-0001",
  from_first_page_version: "FPV-1",
  to_first_page_version: "FPV-2",
  content_version: "CV-1",
  copy_version: "CV-1",
  visual_plan_version: "VV-1",
  revision_classification: "RENDER_ONLY",
  layout_changes: ["Increase title size"],
  typography_changes: [],
  color_changes: [],
  graphic_changes: [],
  copy_change_requested: false,
  visual_plan_change_required: false,
  content_revision_required: false,
  preserved_elements: ["Approved copy"],
  invalidated_artifacts: ["FPV-1 G4 eligibility"],
  requires_rerender: true,
  requires_new_g4: true,
  created_at: at,
  run_id: runId,
  schema_version: "1.0.0",
  extensions: {},
};
const fixtures: Record<string, Record<string, unknown>> = {
  "renderer-config": rendererConfig,
  "renderer-capability-report": capability,
  "renderer-environment-evidence": environment,
  "render-template-manifest": template,
  "first-page-production-plan": plan,
  "first-page-production-report": report,
  "first-page-review": review,
  "first-page-revision-plan": revision,
};
for (const [name, value] of Object.entries(fixtures)) {
  const valid = path.join(root, name, "valid");
  const invalid = path.join(root, name, "invalid");
  await mkdir(valid, { recursive: true });
  await mkdir(invalid, { recursive: true });
  await writeFile(path.join(valid, "complete.json"), `${JSON.stringify(value, null, 2)}\n`);
  const first = Object.keys(value)[0] as string;
  const missing = { ...value };
  delete missing[first];
  await writeFile(
    path.join(invalid, "missing-required.json"),
    `${JSON.stringify(missing, null, 2)}\n`,
  );
  await writeFile(
    path.join(invalid, "additional-property.json"),
    `${JSON.stringify({ ...value, unexpected: true }, null, 2)}\n`,
  );
}
await writeFile(
  path.join(root, "first-page-review", "valid", "revise.json"),
  `${JSON.stringify(reviseReview, null, 2)}\n`,
);

const hostRasterPlan = {
  ...plan,
  first_page_production_plan_id: "FPPP-PHASE4B-HOST-001",
  asset_strategy: "AI_GENERATED_VISUAL",
  programmatic_graphic_plan: null,
  host_generated_asset_plan: {
    generation_id: "GEN-PHASE4B-HOST-001",
    asset_id: "AST-PHASE4B-HOST-001",
    relative_path: "projects/demo/runs/run/image-production/source-assets/background.png",
    checksum: "4".repeat(64),
    mime_type: "image/png",
    width: 1086,
    height: 1448,
    source_type: "HOST_NATIVE_IMAGEGEN",
    contains_formal_copy: false,
    contains_remote_url: false,
  },
  expected_outputs: plan.expected_outputs.map((item) =>
    item === "BACKGROUND_SVG" ? "BACKGROUND_RASTER" : item,
  ),
  plan_hash: "5".repeat(64),
};
await writeFile(
  path.join(root, "first-page-production-plan", "valid", "host-raster.json"),
  `${JSON.stringify(hostRasterPlan, null, 2)}\n`,
);
