import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve("tests/fixtures/contracts/1.0");
const PROJECT_ID = "PRJ-20990101-DEMO";
const CONTENT_ID = "C-0001";
const RUN_ID = "RUN-20990101-010203-DEMO";
const AT = "2099-01-01T01:02:03.000Z";
const HASH = "a".repeat(64);

async function writeJson(file: string, value: unknown): Promise<void> {
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

const asset = (suffix: string, sourceType = "PROGRAMMATIC") => ({
  asset_id: `AST-${suffix}`,
  asset_role: "DIRECTION_CANDIDATE",
  asset_type: "IMAGE",
  mime_type: "image/png",
  relative_path: `projects/demo/direction-candidates/${suffix.toLowerCase()}.png`,
  source_type: sourceType,
  source_adapter:
    sourceType === "HOST_NATIVE_IMAGEGEN" ? "host-native-imagegen" : "pure-typography",
  source_run_id: RUN_ID,
  source_generation_id: `GEN-${suffix}`,
  version: 1,
  width: 1242,
  height: 1660,
  file_size: 2048,
  checksum: HASH,
  created_at: AT,
  extensions: {},
});

const binding = { pack_id: "PROFESSIONAL_SERVICES", pack_version: "1.0.0" };
const overlay = { overlay_id: "BRAND_ASSET_INTEGRITY", overlay_version: "1.0.0" };
const dimensions = [
  ["CONTENT_SEMANTIC_FIT", 20],
  ["COMPOSITION_FOCUS", 15],
  ["HIERARCHY_READABILITY", 15],
  ["ASSET_QUALITY_INTEGRITY", 15],
  ["PROJECT_AUDIENCE_FIT", 10],
  ["UNIQUENESS_ANTI_TEMPLATE", 10],
  ["VISUAL_MODE_EXECUTION", 10],
  ["PLATFORM_MOBILE_PERFORMANCE", 5],
].map(([dimension, weight]) => ({
  dimension,
  weight,
  rating: 4,
  weighted_score: Number(weight) * 0.8,
}));

const fixtures: Record<string, unknown> = {
  "image-production-policy": {
    policy_id: "IMAGE-PRODUCTION-SPEC-V1",
    policy_version: "1.0.0",
    asset_channels: [
      "PROJECT_ASSET",
      "AI_GENERATED_VISUAL",
      "PROGRAMMATIC_GRAPHIC",
      "EVIDENCE_ASSET",
      "PURE_TYPOGRAPHY",
      "MIXED_ASSET",
    ],
    visual_modes: [
      "SCENE_SERIES",
      "EDITORIAL_SERIES",
      "PRODUCT_LIFESTYLE",
      "EVIDENCE_LED",
      "MIXED",
      "CHARACTER_SERIES",
      "PURE_TYPOGRAPHY",
    ],
    candidate_count: { minimum: 2, maximum: 3 },
    final_page_count_range: { minimum: 4, maximum: 8 },
    candidate_quality_threshold: 75,
    formal_quality_threshold: 85,
    hard_blocks: ["FAKE_EVIDENCE", "UNREADABLE_TEXT", "IDENTITY_MISMATCH"],
    formal_text_renderer_only: true,
    production_mock_fallback: false,
    schema_version: "1.0.0",
  },
  "image-production-context": {
    context_id: "IPC-C-0001-R1",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    content_version: "CV-1",
    copy_version: "CV-1",
    visual_plan_version: "VV-1",
    page_count: 6,
    project_visual_profile_maturity: "UNMATURE",
    direction_selection_status: "AWAITING_USER_SELECTION",
    host_imagegen_capability: "READY",
    industry_pack_binding: binding,
    overlay_bindings: [overlay],
    rejected_directions: ["GENERIC_CARD_TEMPLATE"],
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "cover-conversion-plan": {
    cover_conversion_plan_id: "CCP-C-0001-DEMO",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    content_version: "CV-1",
    copy_version: "CV-1",
    platform: "XIAOHONGSHU",
    account_goal: "LEAD_GENERATION",
    cover_objective: "PAINPOINT_DIRECT",
    subject: "Fictional commercial-space advisory studio",
    audience: "Fictional independent store owners",
    painpoint: "A storefront fails to communicate category and positioning at first glance.",
    content_value: "A practical first-impression diagnostic.",
    decision_stage: "Storefront renovation consideration",
    publish_title: "Fictional storefront diagnostic",
    page_1_content_copy: "The first impression should communicate category and positioning.",
    strategy_candidates: ["PAINPOINT_FIRST", "TARGET_AUDIENCE_FIRST", "QUESTION_FIRST"],
    selected_strategy: "PAINPOINT_FIRST",
    primary_hook_constraints: {
      recommended_min_visible_characters: 6,
      recommended_max_visible_characters: 16,
      hard_max_visible_characters: 20,
      max_lines: 3,
    },
    secondary_line_constraints: {
      recommended_min_visible_characters: 0,
      recommended_max_visible_characters: 16,
      hard_max_visible_characters: 20,
      max_lines: 2,
    },
    thumbnail_constraints: {
      targets: ["310x414", "186x248"],
      primary_min_effective_font_px: 28,
      secondary_min_effective_font_px: 14,
      primary_max_lines: 3,
    },
    project_visual_profile_version: null,
    global_visual_preference_version: "GUVPV-1",
    industry_pack_version: "1.0.0",
    platform_pack_version: "1.1.0",
    ambiguities: [],
    blocking_questions: [],
    ready: true,
    plan_hash: HASH,
    run_id: RUN_ID,
    created_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "cover-copy-package": {
    cover_copy_package_id: "CCPK-C-0001-A",
    content_id: CONTENT_ID,
    content_version: "CV-1",
    copy_version: "CV-1",
    cover_copy_version: "CCV-1",
    publish_title: "Fictional storefront diagnostic",
    cover_primary_hook: "生意不好，先看门头",
    cover_secondary_line: "第一眼就劝退顾客？",
    cover_supporting_copy: "",
    page_1_content_copy: "The first impression should communicate category and positioning.",
    cover_objective: "PAINPOINT_DIRECT",
    conversion_strategy: "PAINPOINT_FIRST",
    target_customer_signal: { present: true, text: "Storefront scene filters store owners." },
    painpoint_signal: { present: true, text: "The hook names the first-impression problem." },
    value_signal: { present: false, text: "Value is deferred to the content body." },
    risk_signal: { present: true, text: "The secondary line frames a supported risk." },
    decision_signal: { present: false, text: "No unsupported decision promise." },
    character_counts: {
      publish_title: 31,
      cover_primary_hook: 9,
      cover_secondary_line: 9,
      cover_supporting_copy: 0,
    },
    line_limits: { primary: 2, secondary: 1, supporting: 0 },
    claim_refs: ["P-DYN-SPACE-001"],
    content_alignment: "ALIGNED",
    misleading_risk: "LOW",
    ready_for_g3: true,
    created_at: AT,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    extensions: {},
  },
  "cover-thumbnail-qa": {
    report_id: "CTQA-C-0001-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    candidate_id: "CCC-C-0001-A",
    source_asset_checksum: HASH,
    thumbnails: [
      {
        size: "310x414",
        width: 310,
        height: 414,
        relative_path: "projects/demo/thumbnails/a-310.png",
        checksum: HASH,
        primary_effective_font_px: 31,
        secondary_effective_font_px: 15,
        readable: true,
      },
      {
        size: "186x248",
        width: 186,
        height: 248,
        relative_path: "projects/demo/thumbnails/a-186.png",
        checksum: HASH,
        primary_effective_font_px: 19,
        secondary_effective_font_px: 9,
        readable: true,
      },
    ],
    primary_hook_lines: 2,
    primary_hook_first_focus: true,
    single_click_message: true,
    audience_or_painpoint_or_value_clear: true,
    background_competes: false,
    small_paragraph_present: false,
    text_background_contrast: 7.2,
    text_visual_share: 0.42,
    business_scene_recognizable: true,
    hard_blocks: [],
    result: "PASS",
    run_id: RUN_ID,
    created_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "cover-click-clarity-report": {
    report_id: "CCCR-C-0001-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    candidate_id: "CCC-C-0001-A",
    account_goal: "LEAD_GENERATION",
    cover_objective: "PAINPOINT_DIRECT",
    dimensions: [
      {
        dimension: "TARGET_CUSTOMER_CLARITY",
        weight: 25,
        score: 23,
        reason: "Store owners recognize the scene.",
      },
      {
        dimension: "PAINPOINT_OR_VALUE_CLARITY",
        weight: 25,
        score: 24,
        reason: "The first-impression painpoint is direct.",
      },
      {
        dimension: "ONE_SECOND_COMPREHENSION",
        weight: 20,
        score: 18,
        reason: "One click message.",
      },
      {
        dimension: "THUMBNAIL_LEGIBILITY",
        weight: 20,
        score: 18,
        reason: "Both true-size thumbnails remain legible.",
      },
      {
        dimension: "CONTENT_PROMISE_ALIGNMENT",
        weight: 10,
        score: 9,
        reason: "The promise is supported by the content.",
      },
    ],
    total_score: 92,
    threshold: 85,
    hard_blocks: [],
    result: "PASS_PENDING_OPERATOR",
    operator_approval_required: true,
    run_id: RUN_ID,
    created_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "visual-semantic-relevance-report": {
    report_id: "VSRR-C-0001-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    candidate_id: "CCC-C-0001-A",
    semantic_role: "DIRECT_PAINPOINT_SCENE",
    direct_relation_statement:
      "The complete storefront directly represents the first-impression problem.",
    dimensions: [
      {
        dimension: "INDUSTRY_RELEVANCE",
        weight: 20,
        score: 20,
        reason: "Commercial storefront is explicit.",
      },
      {
        dimension: "BUSINESS_SCENE_RELEVANCE",
        weight: 20,
        score: 19,
        reason: "The operating entrance is visible.",
      },
      {
        dimension: "PAINPOINT_RELEVANCE",
        weight: 20,
        score: 19,
        reason: "Recognition weakness is visible.",
      },
      {
        dimension: "CONTENT_VALUE_RELEVANCE",
        weight: 15,
        score: 13,
        reason: "The image supports diagnosis.",
      },
      {
        dimension: "PROJECT_OR_SUBJECT_RELEVANCE",
        weight: 15,
        score: 13,
        reason: "It matches the fictional subject.",
      },
      {
        dimension: "AUDIENCE_RECOGNITION",
        weight: 10,
        score: 9,
        reason: "Store owners can self-identify.",
      },
    ],
    total_score: 93,
    threshold: 80,
    hard_blocks: [],
    result: "PASS_PENDING_OPERATOR",
    operator_approval_required: true,
    run_id: RUN_ID,
    created_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "cover-concept-candidate-set": {
    candidate_set_id: "CCCS-C-0001-DEMO",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    account_goal: "LEAD_GENERATION",
    status: "AWAITING_USER_SELECTION",
    candidates: ["A", "B", "C"].map((suffix, index) => ({
      candidate_id: `CCC-C-0001-${suffix}`,
      cover_copy_package_id: `CCPK-C-0001-${suffix}`,
      cover_primary_hook: ["生意不好，先看门头", "门店老板，先改第一眼", "你的门头，在劝退顾客吗"][
        index
      ],
      cover_secondary_line: ["第一眼就劝退顾客？", "门头先讲清品类和定位", "先查这3个第一眼信号"][
        index
      ],
      conversion_strategy: ["PAINPOINT_FIRST", "TARGET_AUDIENCE_FIRST", "QUESTION_FIRST"][index],
      cover_objective: ["PAINPOINT_DIRECT", "AUDIENCE_FILTER", "RISK_WARNING"][index],
      asset_channel: "AI_GENERATED_VISUAL",
      visual_mode: ["SCENE_SERIES", "EDITORIAL_SERIES", "MIXED"][index],
      background_semantic_role: [
        "DIRECT_PAINPOINT_SCENE",
        "DIRECT_CUSTOMER_SCENE",
        "DIRECT_BUSINESS_SCENE",
      ][index],
      composition_summary: "A materially distinct commercial storefront direction.",
      text_to_image_ratio: ["42:58", "52:48", "38:62"][index],
      full_preview_ref: `projects/demo/candidates/${suffix}-full.png`,
      thumbnail_310_ref: `projects/demo/candidates/${suffix}-310.png`,
      thumbnail_186_ref: `projects/demo/candidates/${suffix}-186.png`,
      click_clarity_report_id: `CCCR-C-0001-${suffix}`,
      semantic_relevance_report_id: `VSRR-C-0001-${suffix}`,
      image_quality_report_id: `IQR-C-0001-${suffix}`,
      click_clarity_score: 90 + index,
      semantic_relevance_score: 90 + index,
      image_quality_score: 88 + index,
      hard_blocks: [],
      main_strength: "Direct business relevance.",
      main_risk: "Operator aesthetic review remains required.",
      host_imagegen: true,
      renderer: true,
    })),
    full_contact_sheet_ref: "projects/demo/contact-sheets/full.png",
    thumbnail_310_contact_sheet_ref: "projects/demo/contact-sheets/310.png",
    thumbnail_186_contact_sheet_ref: "projects/demo/contact-sheets/186.png",
    material_difference_verified: true,
    formal_fpv_count: 0,
    g4_count: 0,
    style_lock_count: 0,
    feishu_write_count: 0,
    run_id: RUN_ID,
    created_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "cover-revision-plan": {
    revision_plan_id: "CRP-C-0001-R2",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    source_content_version: "CV-1",
    source_copy_version: "CV-1",
    source_visual_plan_version: "VV-2",
    source_first_page_version: "FPV-2",
    source_asset_checksum: HASH,
    revision_routes: ["CONTENT_COPY", "GLOBAL_VISUAL_DIRECTION"],
    next_content_version: "CV-2",
    next_copy_version: "CV-2",
    next_cover_copy_version: "CCV-1",
    requires_new_g3: true,
    preserve_source_asset: true,
    negative_reference_scope: "CURRENT_SET",
    next_action: "COVER_COPY_REVISION_REQUIRED",
    run_id: RUN_ID,
    created_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "global-user-visual-preference": {
    preference_id: "GUVP-DEFAULT",
    preference_version: "GUVPV-1",
    active_rule_refs: ["VR-GLOBAL-COVER-001@1"],
    supersedes_version: null,
    confirmed_by_operator: true,
    source_event_id: "VFE-GLOBAL-COVER-001",
    run_id: RUN_ID,
    created_at: AT,
    updated_at: AT,
    schema_version: "1.0.0",
    extensions: {},
  },
  "dynamic-visual-strategy-plan": {
    strategy_plan_id: "DVSP-C-0001-DEMO",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    project_profile_version: "PVPFV-1",
    profile_maturity_status: "COLD_START",
    synthesis_status: "PLANNED",
    strategy_summary: "A fictional per-content editorial verification strategy.",
    decision_precedence: [
      "SAFETY_AUTHENTICITY_AUTHORIZATION",
      "OPERATOR_CURRENT_REQUEST",
      "CONFIRMED_PROJECT_RULES_AND_PROFILE",
      "PER_CONTENT_SEMANTIC_NEED",
      "INDUSTRY_PACK_PRIOR",
    ],
    page_strategies: [
      {
        page_number: 1,
        page_role: "COVER",
        asset_channel: "PROGRAMMATIC_GRAPHIC",
        visual_mode: "EDITORIAL_SERIES",
        background_direction: "Warm neutral field derived from the fictional content.",
        image_subject: "A precise relationship structure.",
        composition_direction: "Asymmetric title field and relational visual focus.",
        image_realism: "Diagrammatic and non-evidentiary.",
        color_strategy: "Low-saturation neutral with one restrained accent.",
        typography: {
          font_character: "Editorial sans",
          title_size_strategy: "Mobile-recognizable primary title",
          body_size_strategy: "Readable secondary explanation",
          font_weight: "Strong title and regular body",
          line_height: "Comfortable editorial rhythm",
          letter_spacing: "Language-appropriate restrained tracking",
          alignment: "Left aligned",
          text_region: "Left safe-area field",
          text_image_ratio: "45:55",
        },
        effects: {
          effects: ["Restrained boundary line"],
          mask: "None",
          shadow: "None",
          gradient: "None",
          border: "Content-derived boundary",
          texture: "Subtle paper grain",
        },
        selection_reason:
          "The content explains a relationship rather than claiming visual evidence.",
      },
    ],
    candidate_directions: [
      {
        candidate_key: "DIRECTION-C-0001-1",
        asset_channel: "PROGRAMMATIC_GRAPHIC",
        visual_mode: "EDITORIAL_SERIES",
        subject_direction: "Relationship structure",
        composition_direction: "Asymmetric editorial diagram",
        palette_direction: "Warm low-saturation neutral",
        material_difference_basis: "Precise structural explanation",
      },
      {
        candidate_key: "DIRECTION-C-0001-2",
        asset_channel: "AI_GENERATED_VISUAL",
        visual_mode: "EDITORIAL_SERIES",
        subject_direction: "Text-free verification metaphor",
        composition_direction: "Single-object visual metaphor",
        palette_direction: "Warm low-saturation neutral",
        material_difference_basis: "Semantic metaphor rather than diagram",
      },
    ],
    image_count: 1,
    candidate_count: 2,
    production_batches: [{ batch_number: 1, page_numbers: [1], gate: "DIRECTION_SELECTION" }],
    quality_thresholds: {
      direction_candidate: 75,
      formal_asset: 85,
      group: 85,
      core_dimension_floor: 3,
    },
    consistency_risks: ["Do not fabricate evidence."],
    confidence_report_id: "VSCR-C-0001-DEMO",
    ambiguity_report_id: "VAR-C-0001-DEMO",
    selection_reasons: ["Per-content semantics outrank Pack defaults."],
    current_override_applied: false,
    cover_visual_strategy: "PAINPOINT_FIRST",
    cover_text_prominence: "Primary hook is the first visual focus.",
    cover_text_to_image_ratio: "42:58",
    cover_background_semantic_role: "DIRECT_PAINPOINT_SCENE",
    cover_thumbnail_targets: ["310x414", "186x248"],
    cover_click_clarity_target: 85,
    semantic_relevance_target: 80,
    cover_candidate_count: 2,
    cover_candidate_diversity_reason: "Candidates differ in semantic role and composition.",
    long_term_profile_mutated: false,
    industry_pack_mutated: false,
    global_preference_mutated: false,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-strategy-confidence-report": {
    report_id: "VSCR-C-0001-DEMO",
    strategy_plan_id: "DVSP-C-0001-DEMO",
    overall_confidence: 0.72,
    confidence_level: "MEDIUM",
    dimensions: [
      { dimension: "SOURCE_COVERAGE", score: 0.8, reason: "Eight source groups are available." },
      { dimension: "PROFILE_MATURITY", score: 0.62, reason: "Profile is COLD_START." },
    ],
    source_coverage: {
      required_source_count: 10,
      available_source_count: 8,
      missing_sources: ["APPROVED_REFERENCE", "HISTORICAL_GATE_RESULT"],
    },
    review_required: false,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-ambiguity-report": {
    report_id: "VAR-C-0001-DEMO",
    strategy_plan_id: "DVSP-C-0001-DEMO",
    major_ambiguities: [
      {
        code: "COLD_START_AESTHETIC_UNCERTAINTY",
        severity: "MEDIUM",
        description: "No confirmed project visual direction exists yet.",
        affected_decisions: ["PALETTE", "TYPOGRAPHY", "COMPOSITION"],
      },
    ],
    blocking: false,
    recommended_clarification_questions: ["Which direction best represents the project?"],
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-asset-routing-plan": {
    routing_plan_id: "VARP-C-0001-R1",
    context_id: "IPC-C-0001-R1",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    routes: [
      {
        page_number: 1,
        asset_channel: "AI_GENERATED_VISUAL",
        visual_mode: "EDITORIAL_SERIES",
        purpose: "Create a professional direction candidate.",
        formal_text_policy: "RENDERER_ONLY",
        requires_authorization: false,
      },
    ],
    priority_order: [
      "SAFETY",
      "OPERATOR_REQUEST",
      "STYLE_LOCK",
      "PROJECT_PROFILE",
      "GLOBAL_PREFERENCE",
      "EVIDENCE_NEED",
      "INDUSTRY_PACK",
      "VISUAL_MODE",
      "GENERIC",
    ],
    requires_direction_candidates: true,
    blocked_reasons: [],
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-direction-candidate-set": {
    candidate_set_id: "VDCS-C-0001-R1",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    content_version: "CV-1",
    copy_version: "CV-1",
    source_visual_plan_version: "VV-1",
    status: "AWAITING_USER_SELECTION",
    candidates: [
      {
        candidate_id: "VDC-C-0001-A",
        asset_id: "AST-CANDIDATE-A",
        asset_channel: "AI_GENERATED_VISUAL",
        visual_mode: "EDITORIAL_SERIES",
        composition_summary: "Asymmetric editorial object with restrained depth.",
        palette: ["#18232D", "#D8B887"],
        typography_character: "Quiet editorial authority",
        asset: asset("CANDIDATE-A", "HOST_NATIVE_IMAGEGEN"),
        quality_score: 82,
        hard_blocks: [],
        host_imagegen: true,
        renderer: true,
        delivery_role: "DIRECTION_CANDIDATE_ONLY",
      },
      {
        candidate_id: "VDC-C-0001-B",
        asset_id: "AST-CANDIDATE-B",
        asset_channel: "PURE_TYPOGRAPHY",
        visual_mode: "PURE_TYPOGRAPHY",
        composition_summary: "High-contrast typographic field with controlled whitespace.",
        palette: ["#F4EFE6", "#1C1B19"],
        typography_character: "Contemporary magazine",
        asset: asset("CANDIDATE-B"),
        quality_score: 80,
        hard_blocks: [],
        host_imagegen: false,
        renderer: true,
        delivery_role: "DIRECTION_CANDIDATE_ONLY",
      },
    ],
    material_difference_verified: true,
    formal_delivery_count: 0,
    feishu_formal_write_count: 0,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-direction-comparison-set": {
    comparison_set_id: "VDCPS-C-0001-R1",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    source_candidate_set_id: "VDCS-C-0001-R1",
    source_run_id: RUN_ID,
    feedback_event_id: "VFE-C-0001-COMPARISON",
    status: "AWAITING_USER_SELECTION",
    approved_copy: {
      title: "Fictional approved title",
      body: "Fictional approved body used equally across all previews.",
      approved_text_only: true,
      renderer_only: true,
    },
    preview_conditions: {
      width: 1242,
      height: 1660,
      aspect_ratio: "3:4",
      same_copy: true,
      same_scale_in_contact_sheet: true,
      candidate_labels_outside_frames: true,
      text_overflow_free: true,
      mobile_title_legible: true,
    },
    previews: ["A", "B", "C"].map((suffix, index) => ({
      candidate_id: `VDC-C-0001-${suffix}`,
      original_asset_id: `AST-CANDIDATE-${suffix}`,
      original_checksum: HASH,
      preview_asset: {
        ...asset(`CANDIDATE-${suffix}-COMPLETE-PREVIEW`),
        source_adapter: "PlaywrightHtmlCssRendererAdapter",
      },
      asset_channel:
        index === 0 ? "AI_GENERATED_VISUAL" : index === 1 ? "PURE_TYPOGRAPHY" : "MIXED_ASSET",
      visual_mode: index === 0 ? "EDITORIAL_SERIES" : index === 1 ? "PURE_TYPOGRAPHY" : "MIXED",
      quality_report_id: `IQR-C-0001-${suffix}-COMPLETE-PREVIEW`,
      quality_score: 86 + index,
      content_match_strength: "Approved copy is fully rendered in the candidate language.",
      aesthetic_risk: "Operator aesthetic review remains required.",
      mobile_thumbnail_performance: "PASS",
      host_imagegen_dependency: index !== 1,
      renderer_dependency: true,
    })),
    contact_sheet_asset: {
      ...asset("CANDIDATE-CONTACT-SHEET"),
      asset_role: "REFERENCE",
      width: 2400,
      height: 1200,
      source_adapter: "PlaywrightHtmlCssRendererAdapter",
    },
    long_term_rule_candidate: false,
    formal_delivery_count: 0,
    feishu_formal_write_count: 0,
    vv2_created: false,
    fpv2_created: false,
    g4_created: false,
    style_lock_created: false,
    remaining_pages_created: 0,
    idempotency_key: HASH,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-direction-selection": {
    selection_id: "VDS-C-0001-A",
    candidate_set_id: "VDCS-C-0001-R1",
    candidate_id: "VDC-C-0001-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    selected_by: "OPERATOR",
    selection_comment: "Fictional fixture selection.",
    creates_g4: false,
    creates_style_lock: false,
    next_visual_plan_version: "VV-2",
    run_id: RUN_ID,
    schema_version: "1.0.0",
    selected_at: AT,
  },
  "image-production-batch-plan": {
    batch_plan_id: "IPBP-C-0001-R1",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    content_version: "CV-1",
    copy_version: "CV-1",
    visual_plan_version: "VV-1",
    style_lock_version: null,
    final_page_count: 6,
    source_asset_count: 0,
    direction_candidate_count: 2,
    formal_candidate_count: 0,
    generation_attempt_count: 2,
    failed_attempt_count: 0,
    retained_history_count: 2,
    pages: Array.from({ length: 6 }, (_, index) => ({
      page_number: index + 1,
      asset_channel: index === 0 ? "MIXED_ASSET" : "AI_GENERATED_VISUAL",
      status: "BLOCKED_BY_G4",
    })),
    requires_g4: true,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "image-quality-report": {
    report_id: "IQR-C-0001-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    asset_id: "AST-CANDIDATE-A",
    asset_role: "DIRECTION_CANDIDATE",
    layers: {
      authenticity_and_integrity: "PASS",
      mechanical: "PASS",
      visual: "PASS",
      mode_and_project_fit: "PASS",
      operator_aesthetic: "PENDING",
    },
    dimensions,
    total_score: 80,
    threshold: 75,
    hard_blocks: [],
    core_dimension_floor_met: true,
    operator_approval_required: true,
    result: "PASS_PENDING_OPERATOR",
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "group-quality-report": {
    report_id: "GQR-C-0001-R1",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    visual_mode: "EDITORIAL_SERIES",
    asset_ids: ["AST-CANDIDATE-A", "AST-CANDIDATE-B"],
    system_consistency: { status: "PASS", notes: [] },
    subject_consistency: { status: "PASS", notes: [] },
    page_difference: { status: "PASS", notes: ["Candidates are materially different."] },
    near_duplicate_pairs: [],
    source_reuse_findings: [],
    contact_sheet_ref: "projects/demo/contact-sheets/candidates.png",
    hard_blocks: [],
    operator_approval_required: true,
    result: "PASS_PENDING_OPERATOR",
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "host-generated-asset-submission": {
    submission_id: "HGAS-C-0001-A",
    generation_id: "GEN-CANDIDATE-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    candidate_id: "VDC-C-0001-A",
    source_kind: "LOCAL_FILE",
    source_path: "/private/tmp/host-output.png",
    temporary_url: null,
    declared_mime_type: "image/png",
    expected_role: "DIRECTION_CANDIDATE",
    host_provider: "CODEX_HOST_IMAGEGEN",
    host_model: null,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    submitted_at: AT,
  },
  "project-visual-profile": {
    profile_id: "PVPF-DEMO",
    project_id: PROJECT_ID,
    profile_version: "PVPFV-1",
    maturity: "COLD_START",
    maturity_status: "COLD_START",
    industry_pack_binding: binding,
    overlay_bindings: [overlay],
    preferred_visual_modes: [],
    preferred_asset_channels: [],
    identity_invariants: ["Keep the fictional subject identity stable."],
    confirmed_preferences: [],
    rejected_directions: ["GENERIC_CARD_TEMPLATE"],
    approved_reference_assets: [],
    source_rule_versions: [],
    asset_source_preferences: [],
    background_preferences: [],
    image_realism_preferences: [],
    photography_preferences: [],
    illustration_preferences: [],
    character_preferences: [],
    space_preferences: [],
    product_preferences: [],
    composition_preferences: [],
    visual_focus_preferences: [],
    whitespace_preferences: [],
    visual_density_preferences: [],
    typography_preferences: [],
    font_family_preferences: [],
    title_size_preferences: [],
    body_size_preferences: [],
    font_weight_preferences: [],
    line_height_preferences: [],
    letter_spacing_preferences: [],
    alignment_preferences: [],
    color_preferences: [],
    accent_color_preferences: [],
    contrast_preferences: [],
    effect_preferences: [],
    shadow_preferences: [],
    gradient_preferences: [],
    mask_preferences: [],
    border_preferences: [],
    corner_preferences: [],
    texture_preferences: [],
    formal_text_policy: "RENDERER_ONLY",
    image_text_policy: "TEXT_FREE_GENERATED_VISUALS",
    preferred_page_counts: [6],
    preferred_candidate_counts: [2, 3],
    production_batch_preferences: ["First page before remaining pages"],
    quality_thresholds: {
      direction_candidate: 75,
      formal_asset: 85,
      group: 85,
      core_dimension_floor: 3,
    },
    approved_reference_elements: [],
    rejected_reference_elements: ["Generic card grid"],
    must_rules: [],
    must_not_rules: [],
    prefer_rules: [],
    avoid_rules: ["Generic card grid"],
    confirmed_feedback_refs: [],
    rule_version_refs: [],
    known_exceptions: [],
    review_required_reasons: [],
    cover_account_goal_preferences: ["LEAD_GENERATION"],
    cover_objective_preferences: ["PAINPOINT_DIRECT", "AUDIENCE_FILTER"],
    cover_primary_hook_length_preferences: ["6-16 visible characters"],
    cover_primary_hook_line_preferences: ["Maximum 3 lines"],
    cover_secondary_line_preferences: ["Maximum 2 lines"],
    cover_text_prominence_preferences: ["Primary hook first"],
    cover_text_area_preferences: ["Large safe-area text field"],
    cover_text_to_image_ratio_preferences: ["42:58"],
    cover_thumbnail_font_preferences: ["Readable at 310x414 and 186x248"],
    cover_alignment_preferences: ["Composition-derived"],
    cover_contrast_preferences: ["WCAG-like text contrast"],
    cover_effect_preferences: ["Restrained and semantic"],
    cover_background_semantic_preferences: ["DIRECT_BUSINESS_SCENE"],
    cover_approved_reference_elements: [],
    cover_rejected_reference_elements: ["Decorative-only backgrounds"],
    confirmed_by_operator: false,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
    updated_at: AT,
  },
  "visual-feedback-event": {
    event_id: "VFE-C-0001-A",
    project_id: PROJECT_ID,
    content_id: CONTENT_ID,
    feedback_class: "VISUAL_PREFERENCE",
    scope: "CURRENT_SET",
    target_type: "SET",
    target_id: "VDCS-C-0001-R1",
    statement: "Prefer the quieter editorial direction for this set.",
    is_tool_or_system_defect: false,
    long_term_rule_candidate: false,
    creates_long_term_rule: false,
    source: "OPERATOR_FEEDBACK",
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-rule-candidate": {
    candidate_id: "VRC-C-0001-A",
    project_id: PROJECT_ID,
    source_event_id: "VFE-C-0001-A",
    rule_statement: "Prefer quiet editorial compositions.",
    rationale: "Derived from explicit fictional Operator feedback.",
    scope: "CURRENT_PROJECT",
    rule_type: "PREFER",
    positive_examples: ["Controlled whitespace"],
    negative_examples: ["Generic card grid"],
    allowed_exceptions: ["Evidence-led pages"],
    confirmed_by_user: false,
    status: "CANDIDATE",
    version: 1,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
  },
  "visual-rule": {
    rule_id: "VR-DEMO-001",
    project_id: PROJECT_ID,
    source_event_id: "VFE-C-0001-A",
    source_candidate_id: "VRC-C-0001-A",
    global_preference_version: null,
    rule_statement: "Prefer quiet editorial compositions.",
    rationale: "Explicit fictional confirmation.",
    scope: "CURRENT_PROJECT",
    rule_type: "PREFER",
    positive_examples: ["Controlled whitespace"],
    negative_examples: ["Generic card grid"],
    allowed_exceptions: ["Evidence-led pages"],
    confirmed_by_user: true,
    status: "ACTIVE",
    version: 1,
    supersedes_version: null,
    run_id: RUN_ID,
    schema_version: "1.0.0",
    created_at: AT,
    updated_at: AT,
  },
  "industry-visual-pack": {
    pack_id: "PROFESSIONAL_SERVICES",
    pack_version: "1.0.0",
    display_name: "Professional Services",
    supported_industries: ["Fictional advisory services"],
    default_visual_mode_ranking: ["EDITORIAL_SERIES", "EVIDENCE_LED", "PURE_TYPOGRAPHY"],
    asset_source_priority: [
      "PROJECT_ASSET",
      "EVIDENCE_ASSET",
      "AI_GENERATED_VISUAL",
      "PURE_TYPOGRAPHY",
    ],
    identity_invariants: ["Do not fabricate a client case."],
    specialized_hard_blocks: ["Fake credentials"],
    specialized_quality_checks: ["Trust signal clarity"],
    consistency_requirements: ["Stable professional tone"],
    fallback_strategies: ["Use pure typography when no lawful image is available."],
    recommended_questions: ["Which trust signal is supported?"],
    prohibited_claims_or_representations: ["Guaranteed outcome"],
    allowed_overlays: ["EVIDENCE_AUTHENTICITY", "BRAND_ASSET_INTEGRITY"],
    known_limitations: ["Does not supply customer assets."],
    contains_customer_assets: false,
    schema_version: "1.0.0",
  },
};

for (const [name, value] of Object.entries(fixtures)) {
  await writeJson(path.join(ROOT, name, "valid", "complete.json"), value);
  await writeJson(path.join(ROOT, name, "invalid", "additional-property.json"), {
    ...(value as Record<string, unknown>),
    unexpected: true,
  });
  const [required] = Object.keys(value as Record<string, unknown>);
  const missing = { ...(value as Record<string, unknown>) };
  if (!required) throw new Error(`Fixture ${name} unexpectedly has no required fields.`);
  delete missing[required];
  await writeJson(path.join(ROOT, name, "invalid", "missing-required.json"), missing);
}

console.log(`Generated image-production fixtures for ${Object.keys(fixtures).length} schemas.`);
